//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormToWCF.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://schemas.datacontract.org/2004/07/ProjectWCF")]
    [System.SerializableAttribute()]
    public partial class Person : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertPersonToDB", ReplyAction="http://tempuri.org/IService1/InsertPersonToDBResponse")]
        int InsertPersonToDB(FormToWCF.ServiceReference1.Person person);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertPersonToDB", ReplyAction="http://tempuri.org/IService1/InsertPersonToDBResponse")]
        System.Threading.Tasks.Task<int> InsertPersonToDBAsync(FormToWCF.ServiceReference1.Person person);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdatePersonToDB", ReplyAction="http://tempuri.org/IService1/UpdatePersonToDBResponse")]
        int UpdatePersonToDB(FormToWCF.ServiceReference1.Person person);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdatePersonToDB", ReplyAction="http://tempuri.org/IService1/UpdatePersonToDBResponse")]
        System.Threading.Tasks.Task<int> UpdatePersonToDBAsync(FormToWCF.ServiceReference1.Person person);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeletePersonToDB", ReplyAction="http://tempuri.org/IService1/DeletePersonToDBResponse")]
        int DeletePersonToDB(FormToWCF.ServiceReference1.Person person);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeletePersonToDB", ReplyAction="http://tempuri.org/IService1/DeletePersonToDBResponse")]
        System.Threading.Tasks.Task<int> DeletePersonToDBAsync(FormToWCF.ServiceReference1.Person person);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectPersonToDB", ReplyAction="http://tempuri.org/IService1/SelectPersonToDBResponse")]
        FormToWCF.ServiceReference1.Person SelectPersonToDB(FormToWCF.ServiceReference1.Person person);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectPersonToDB", ReplyAction="http://tempuri.org/IService1/SelectPersonToDBResponse")]
        System.Threading.Tasks.Task<FormToWCF.ServiceReference1.Person> SelectPersonToDBAsync(FormToWCF.ServiceReference1.Person person);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectAllPersonToDB", ReplyAction="http://tempuri.org/IService1/SelectAllPersonToDBResponse")]
        FormToWCF.ServiceReference1.Person[] SelectAllPersonToDB();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectAllPersonToDB", ReplyAction="http://tempuri.org/IService1/SelectAllPersonToDBResponse")]
        System.Threading.Tasks.Task<FormToWCF.ServiceReference1.Person[]> SelectAllPersonToDBAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : FormToWCF.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<FormToWCF.ServiceReference1.IService1>, FormToWCF.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int InsertPersonToDB(FormToWCF.ServiceReference1.Person person) {
            return base.Channel.InsertPersonToDB(person);
        }
        
        public System.Threading.Tasks.Task<int> InsertPersonToDBAsync(FormToWCF.ServiceReference1.Person person) {
            return base.Channel.InsertPersonToDBAsync(person);
        }
        
        public int UpdatePersonToDB(FormToWCF.ServiceReference1.Person person) {
            return base.Channel.UpdatePersonToDB(person);
        }
        
        public System.Threading.Tasks.Task<int> UpdatePersonToDBAsync(FormToWCF.ServiceReference1.Person person) {
            return base.Channel.UpdatePersonToDBAsync(person);
        }
        
        public int DeletePersonToDB(FormToWCF.ServiceReference1.Person person) {
            return base.Channel.DeletePersonToDB(person);
        }
        
        public System.Threading.Tasks.Task<int> DeletePersonToDBAsync(FormToWCF.ServiceReference1.Person person) {
            return base.Channel.DeletePersonToDBAsync(person);
        }
        
        public FormToWCF.ServiceReference1.Person SelectPersonToDB(FormToWCF.ServiceReference1.Person person) {
            return base.Channel.SelectPersonToDB(person);
        }
        
        public System.Threading.Tasks.Task<FormToWCF.ServiceReference1.Person> SelectPersonToDBAsync(FormToWCF.ServiceReference1.Person person) {
            return base.Channel.SelectPersonToDBAsync(person);
        }
        
        public FormToWCF.ServiceReference1.Person[] SelectAllPersonToDB() {
            return base.Channel.SelectAllPersonToDB();
        }
        
        public System.Threading.Tasks.Task<FormToWCF.ServiceReference1.Person[]> SelectAllPersonToDBAsync() {
            return base.Channel.SelectAllPersonToDBAsync();
        }
    }
}
